version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: tracing-jaeger-aio
    environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
    - 5775:5775/udp
    - 5778:5778
    - 6831:6831/udp
    - 6832:6832/udp
    - 9411:9411
    - 14268:14268
    - 16686:16686
